import express from 'express';
import { signUp } from '../controllers/sign/signUp';
import { signIn } from '../controllers/sign/signIn';
import { getDeviceInfo } from '../middleware/deviceInfo';
import { signUpValidation } from '../middleware/signUpValidation';
import { verifyOtp } from '../controllers/sign/verifyOtp';
import { getUserFromTemp } from '../middleware/getUserFromTemp';
import { resendOtp } from '../controllers/sign/resendOtp';
import { changePassword } from '../controllers/sign/changePassword';
import { getUserFromPermanent } from '../middleware/getUserFromPermanent';
import { getNewAccessToken } from '../controllers/sign/getNewAccessToken';
import { getCurrentUser } from '../controllers/sign/getCurrentUser';
export const signUpInRouter = express.Router();
signUpInRouter.post('/signup', getDeviceInfo, signUpValidation, signUp);
signUpInRouter.post('/signin', getDeviceInfo, signIn);
signUpInRouter.post('/verifyOtp', getDeviceInfo, getUserFromTemp, verifyOtp);
signUpInRouter.get('/resendOtp', getDeviceInfo, getUserFromTemp, resendOtp);
signUpInRouter.patch('/changePassword', getUserFromPermanent, changePassword);
signUpInRouter.get('/getNewAccessToken', getDeviceInfo, getNewAccessToken);
signUpInRouter.get('/getUser', getUserFromPermanent, getCurrentUser);
